name: forall_hr
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+6

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  animated_bottom_navigation_bar:
  cached_network_image:
  connectivity_plus:
  dartz:
  dio:
  google_mobile_ads:
  fl_chart:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  flutter_svg:
  get:
  audio_session:
  get_it:
  get_storage:
  google_maps_flutter:
  image_picker:
  file_picker:
  intl:
  geolocator:
  pinput:
  country_code_picker:
  flutter_speed_dial:
  share_plus:
  photo_view:
  flutter_emoji:
  socket_io_client: ^2.0.0
  shimmer:
  linkwell:
  flutter_sound:
  audioplayers:
  permission_handler:
  flutter_local_notifications:
  firebase_core: ^2.4.0
  firebase_messaging:
  url_launcher:
  syncfusion_flutter_datepicker:
  searchable_listview:
  flutter_credit_card:
  webview_flutter:
  font_awesome_flutter:
  azlistview: 2.0.0
  lit_relative_date_time:
  flutter_slidable:
  image_cropper: ^4.0.1
  cached_network_svg_image: ^0.0.5
  simple_barcode_scanner: ^0.0.8
  flutter_pdfview: ^1.3.1




dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  build_runner:
  flutter_lints:
  freezed: '2.3.2'
  freezed_annotation:
  json_annotation:
  json_serializable:
  flutter_native_splash: #  flutter pub run flutter_native_splash:create
  flutter_launcher_icons: #  flutter pub run flutter_launcher_icons:main
  change_app_package_name: #  flutter pub run change_app_package_name:main com.new.package.name

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/White.jpg"

flutter_native_splash:
  background_image: "assets/launcher/icon.png"
  fullscreen: true
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/launcher/
    - assets/fonts/

  fonts:
    - family: Zaptron
      fonts:
        - asset: assets/fonts/Zaptron-Regular.otf



